### ISSUE TITLE
Add GitHub repository URL to support details in Ubuntu Store

### ISSUE THREAD

**Issue by bittner** [nomelif/ComicShelf#2]
Currently, the [Ubuntu Store](https://uappexplorer.com/app/com.ubuntu.developer.theo.friberg.comicshelf) lists Theo Friberg's email address in the support / contact details.

It would help if the following information may be updated in the Ubuntu Store:

- [ ] **Website:** https://github.com/nomelif/ComicShelf
- [ ] **Support:** https://github.com/nomelif/ComicShelf/issues

... or similar.

**Comment by nomelif** [comment]
Done, sir.

**Comment by bittner** [comment]
Awesome!  :+1:
